# Generated by Django 5.2.4 on 2025-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField(default=2)),
                ('image', models.ImageField(upload_to='rooms_image')),
                ('type', models.CharField(choices=[('standart', 'Стандарт'), ('premium', 'Преміум'), ('deluxe', 'Делюкс')], default='standart', max_length=60)),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
                'ordering': ['price', 'type'],
            },
        ),
    ]
