# Generated by Django 5.2.4 on 2025-07-31 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='назва номера')),
                ('description', models.TextField(verbose_name='опис')),
                ('price', models.IntegerField(verbose_name='ціна')),
                ('capacity', models.IntegerField(default=2, verbose_name='місткість номера')),
                ('image', models.ImageField(upload_to='rooms_image', verbose_name='фото номера')),
                ('type', models.CharField(choices=[('standart', 'Стандарт'), ('premium', 'Преміум'), ('deluxe', 'Делюкс'), ('grand delux', 'Гранд Делюкс'), ('lux', 'Люкс'), ('superlux', 'Суперлюкс'), ('grand superlux', 'Гранд Суперлюкс')], default='standart', max_length=60, verbose_name='клас номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
                'ordering': ['price', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
